apiVersion: v1
kind: Service
metadata:
  name: flask-service  # Name of the service
spec:
  selector:
    app: flask-app  # Selector to link the service to the pods created by the deployment
  ports:
    - protocol: TCP
      port: 80  # Port exposed outside the cluster (external port)
      targetPort: 5000  # Port inside the container where the Flask app is running
  type: LoadBalancer  # This makes the service accessible outside the cluster (only works in cloud providers with LoadBalancer support)
